import Foundation

/// Canonical CleanMyMac / BuhoCleaner / CCleaner cleanable category.
/// Paths are user-relative — resolved at scan time, not at compile time.
enum SystemCleanupCategory: String, CaseIterable, Identifiable, Hashable {
    case userCaches
    case appLogs
    case browserCaches
    case xcodeDerivedData
    case xcodeArchives
    case iosSimulatorCaches
    case npmCache
    case yarnCache
    case pipCache
    case homebrewCache
    case mailDownloads
    case trash

    var id: String { rawValue }

    var title: String {
        switch self {
        case .userCaches:        return "User Caches"
        case .appLogs:           return "App Logs"
        case .browserCaches:     return "Browser Caches"
        case .xcodeDerivedData:  return "Xcode DerivedData"
        case .xcodeArchives:     return "Xcode Archives"
        case .iosSimulatorCaches:return "iOS Simulator Caches"
        case .npmCache:          return "npm Cache"
        case .yarnCache:         return "Yarn Cache"
        case .pipCache:          return "pip Cache"
        case .homebrewCache:     return "Homebrew Cache"
        case .mailDownloads:     return "Mail Downloads"
        case .trash:             return "Trash"
        }
    }

    var symbol: String {
        switch self {
        case .userCaches:        return "tray.full"
        case .appLogs:           return "doc.text.magnifyingglass"
        case .browserCaches:     return "safari"
        case .xcodeDerivedData:  return "hammer"
        case .xcodeArchives:     return "archivebox"
        case .iosSimulatorCaches:return "iphone"
        case .npmCache, .yarnCache, .pipCache, .homebrewCache:
            return "shippingbox"
        case .mailDownloads:     return "envelope"
        case .trash:             return "trash"
        }
    }

    /// Should this category be selected by default?
    /// Conservative defaults — Xcode Archives + Mail Downloads are user data,
    /// the rest is regenerated by the system or tools.
    var safeDefault: Bool {
        switch self {
        case .xcodeArchives, .mailDownloads: return false
        default: return true
        }
    }

    /// Resolves to one or more directories under the given home URL.
    /// Returns empty array if the category is not applicable on this Mac.
    func paths(home: URL) -> [URL] {
        switch self {
        case .userCaches:
            return [home.appendingPathComponent("Library/Caches")]
        case .appLogs:
            return [home.appendingPathComponent("Library/Logs")]
        case .browserCaches:
            let lib = home.appendingPathComponent("Library")
            return [
                lib.appendingPathComponent("Caches/com.apple.Safari"),
                lib.appendingPathComponent("Application Support/Google/Chrome/Default/Cache"),
                lib.appendingPathComponent("Application Support/Google/Chrome/Default/Code Cache"),
                lib.appendingPathComponent("Caches/Firefox"),
                lib.appendingPathComponent("Application Support/BraveSoftware/Brave-Browser/Default/Cache"),
                lib.appendingPathComponent("Application Support/Arc/User Data/Default/Cache"),
                lib.appendingPathComponent("Application Support/Microsoft Edge/Default/Cache"),
            ]
        case .xcodeDerivedData:
            return [home.appendingPathComponent("Library/Developer/Xcode/DerivedData")]
        case .xcodeArchives:
            return [home.appendingPathComponent("Library/Developer/Xcode/Archives")]
        case .iosSimulatorCaches:
            return [home.appendingPathComponent("Library/Developer/CoreSimulator/Caches")]
        case .npmCache:
            return [home.appendingPathComponent(".npm/_cacache")]
        case .yarnCache:
            return [
                home.appendingPathComponent("Library/Caches/Yarn"),
                home.appendingPathComponent(".yarn/cache"),
            ]
        case .pipCache:
            return [home.appendingPathComponent("Library/Caches/pip")]
        case .homebrewCache:
            return [home.appendingPathComponent("Library/Caches/Homebrew")]
        case .mailDownloads:
            return [home.appendingPathComponent("Library/Containers/com.apple.mail/Data/Library/Mail Downloads")]
        case .trash:
            return [home.appendingPathComponent(".Trash")]
        }
    }

    /// Directories that should be PRESERVED — only their *contents* get cleaned,
    /// not the directory itself. The Trash and the Caches root must continue
    /// to exist after cleanup.
    var preserveContainer: Bool {
        switch self {
        case .trash, .userCaches, .appLogs, .iosSimulatorCaches:
            return true
        default:
            return false
        }
    }
}
